### ISSUE TITLE
use lame, flac from the runtime

### ISSUE THREAD

**Issue by eszlari** [flathub/ca.littlesvr.asunder#11]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tree/19.08/elements/components

**Comment by Eonfge** [comment]
Flac seems to be an older version (1.3.2) while I package the latest version: 1.3.3. The master is on 1.3.3, so I'll keep this issue open until 20.08 is released. This way, I don't have to downgrade the flac version.

**Comment by Eonfge** [comment]
Both Flac and WavPack will be removed from the flatpak, once we move to 20.08: https://github.com/flathub/ca.littlesvr.asunder/pull/14

**Comment by Eonfge** [comment]
Should be going live in the next hour or so.
