### ISSUE TITLE
Remove exclusive-arch, build for ARM

### ISSUE THREAD

**Issue by hadess** [flathub/ca.littlesvr.asunder#2]
Pretty sure the app can be built for ARM if you manage to build cdparanoia, as per:
https://github.com/flathub/org.gnome.Rhythmbox3/pull/25

Something like:
https://github.com/flathub/org.gnome.Rhythmbox3/blob/wip/hadess/add-audio-cd/org.gnome.Rhythmbox3.json#L142

**Comment by Eonfge** [comment]
I now have an ARM device to test on, so this is certainly something I want to try.

**Comment by Eonfge** [comment]
@hadess Could you test it for me?
[ARM Pull Request](https://github.com/flathub/ca.littlesvr.asunder/pull/3)

**Comment by hadess** [comment]
No, I cannot. But if it builds, wait until you get bug reports.

**Comment by Eonfge** [comment]
Good enough for me. I'll add a 'Caveat Emptor' and then we'll see how it goes.
